In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Admin\Desktop\hhh\Horse\data_preprocessing\merged_data_kr_Nan.csv", encoding="utf-8-sig")

In [ ]:
df.head()

In [ ]:
df.head()

,divide,hrName,hrno,jkNo,prtr,rcBudam,rcChul,rcCode,rcDate,rcDist,...,track,weath,wgHr,damHrnm,foalgDt,gndrNm,owrNm,pctyNm,sireHrnm,sitlNm
0,0,파이널축제,45339,080342,70170.0,2,3,일반,20230107,1300,...,양호,흐림,490.0,월드퀵,2020-03-10(6세),수,럭키,한국,지롤라모,서울경마공원
1,0,아르고리치,45921,080366,70146.0,2,6,일반,20230107,1300,...,양호,흐림,496.0,어너러리갤럽,2020-04-08(6세),수,우태율,한국,컬러즈플라잉,서울경마공원
2,0,파워에치드,45734,080339,70166.0,2,11,일반,20230107,1300,...,양호,흐림,483.0,베트파티,2020-03-18(6세),거,박정재,한국,에치드,서울경마공원
3,0,베스트선,45369,080405,70115.0,3,1,일반,20230107,1300,...,양호,흐림,479.0,아이월이프유월,2020-02-28(6세),거,베스트샤인조합,한국,테이크차지인디,서울경마공원
4,0,슈어윈,45240,080103,70096.0,3,7,일반,20230107,1300,...,양호,흐림,413.0,매그니피센트마인,2020-02-13(6세),암,지성배,한국,BERNARDINI,서울경마공원

In [4]:
df.columns

Index(['divide', 'hrName', 'hrno', 'jkNo', 'prtr', 'rcBudam', 'rcChul',
       'rcCode', 'rcDate', 'rcDist', 'rcGrade', 'rcHrnew', 'rcNo', 'rcNrace',
       'rcOrd', 'rcP1Odd', 'rcP1Sale', 'rcP2Odd', 'rcP2Sale', 'rcP3Odd',
       'rcP3Sale', 'rcP4Odd', 'rcP4Sale', 'rcP5Odd', 'rcP5Sale', 'rcP6Odd',
       'rcP6Sale', 'rcP8Odd', 'rcP8Sale', 'rcPlansu', 'rcRank', 'rcTime',
       'rcVtdusu', 'track', 'weath', 'wgHr', 'damHrnm', 'foalgDt', 'gndrNm',
       'owrNm', 'pctyNm', 'sireHrnm', 'sitlNm'],
      dtype='str')

In [5]:
same_cols = []

cols = df.columns

for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        if df[cols[i]].equals(df[cols[j]]):
            same_cols.append((cols[i], cols[j]))

same_cols

[]

In [6]:
one_value_cols = [col for col in df.columns if df[col].nunique() == 1]
one_value_cols

[]

In [7]:
import numpy as np

corr = df.corr(numeric_only=True)

high_corr = []

for i in range(len(corr.columns)):
    for j in range(i+1, len(corr.columns)):
        if abs(corr.iloc[i, j]) > 0.95:
            high_corr.append((corr.columns[i], corr.columns[j], corr.iloc[i, j]))

high_corr

[]

In [8]:
import numpy as np

corr = df.corr(numeric_only=True)

high_corr = []

for i in range(len(corr.columns)):
    for j in range(i+1, len(corr.columns)):
        if abs(corr.iloc[i, j]) > 0.95:
            high_corr.append((corr.columns[i], corr.columns[j], corr.iloc[i, j]))

high_corr

[]

In [9]:
df.describe()

,divide,hrno,prtr,rcBudam,rcChul,rcDate,rcDist,rcNo,rcOrd,rcP1Odd,...,rcP5Sale,rcP6Odd,rcP6Sale,rcP8Odd,rcP8Sale,rcPlansu,rcRank,rcTime,rcVtdusu,wgHr
count,15948.000000,1.594800e+04,15948.000000,15948.000000,15948.000000,1.594800e+04,15948.000000,15948.000000,15948.000000,15948.000000,...,1.594800e+04,15948.000000,1.594800e+04,15948.000000,1.594800e+04,15948.000000,15948.000000,15780.000000,15948.000000,15948.000000
mean,0.157261,1.188840e+05,70172.340168,2.640645,5.868197,2.024856e+07,1404.326561,5.630048,6.516491,7.697592,...,1.263722e+08,99.602176,1.019481e+09,634.320372,5.189970e+08,10.724730,4.572548,89.963752,10.550853,475.612333
std,0.487865,2.984003e+05,43.560752,0.495261,3.134682,8.746811e+03,231.422226,3.168254,10.927148,10.451594,...,2.981282e+07,263.302209,2.588439e+08,1593.334375,1.222944e+08,1.026872,1.481752,17.405132,1.083917,33.068415
min,0.000000,3.805200e+04,70053.000000,1.000000,1.000000,2.023011e+07,1000.000000,1.000000,1.000000,1.100000,...,4.321330e+07,1.700000,1.303034e+08,5.600000,7.529030e+07,8.000000,0.000000,0.000000,6.000000,0.000000
25%,0.000000,4.678300e+04,70149.000000,2.000000,3.000000,2.024101e+07,1200.000000,3.000000,3.000000,2.400000,...,1.061204e+08,13.300000,8.500943e+08,64.200000,4.394937e+08,10.000000,4.000000,77.000000,10.000000,458.000000
50%,0.000000,5.113700e+04,70167.000000,3.000000,6.000000,2.025061e+07,1300.000000,6.000000,5.000000,4.300000,...,1.267388e+08,30.900000,1.023239e+09,175.400000,5.188399e+08,11.000000,5.000000,85.800000,11.000000,477.000000
75%,0.000000,5.341600e+04,70182.000000,3.000000,8.000000,2.025121e+07,1600.000000,8.000000,8.000000,8.600000,...,1.475799e+08,84.975000,1.202105e+09,532.900000,5.972360e+08,11.000000,6.000000,101.700000,11.000000,495.000000
max,2.000000,1.412351e+06,70306.000000,3.000000,16.000000,2.026043e+07,2300.000000,15.000000,95.000000,152.700000,...,2.343899e+08,5660.800000,1.826407e+09,32254.600000,1.147854e+09,16.000000,16.000000,154.500000,16.000000,573.000000

In [10]:
def outlier_summary(df):
    result = {}

    for col in df.select_dtypes(include='number').columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        count = ((df[col] < lower) | (df[col] > upper)).sum()

        result[col] = count

    return result

print(outlier_summary(df))

{'divide': np.int64(1667), 'hrno': np.int64(806), 'prtr': np.int64(2978), 'rcBudam': np.int64(0), 'rcChul': np.int64(5), 'rcDate': np.int64(0), 'rcDist': np.int64(24), 'rcNo': np.int64(0), 'rcOrd': np.int64(227), 'rcP1Odd': np.int64(1442), 'rcP1Sale': np.int64(102), 'rcP2Odd': np.int64(918), 'rcP2Sale': np.int64(77), 'rcP3Odd': np.int64(1761), 'rcP3Sale': np.int64(38), 'rcP4Odd': np.int64(1976), 'rcP4Sale': np.int64(129), 'rcP5Odd': np.int64(1067), 'rcP5Sale': np.int64(46), 'rcP6Odd': np.int64(1807), 'rcP6Sale': np.int64(35), 'rcP8Odd': np.int64(1946), 'rcP8Sale': np.int64(237), 'rcPlansu': np.int64(968), 'rcRank': np.int64(160), 'rcTime': np.int64(85), 'rcVtdusu': np.int64(1133), 'wgHr': np.int64(103)}

In [11]:
(df['wgHr'] == 0).sum()

np.int64(28)

In [12]:
zero_cols = [col for col in df.columns if (df[col] == 0).any()]
zero_cols

['divide', 'rcRank', 'rcTime', 'wgHr']

In [13]:
(df['rcRank'] == 0).sum()

np.int64(57)

In [14]:
(df['rcTime'] == 0).sum()

np.int64(58)

In [15]:
df["rcTime"].isnull().sum()

np.int64(168)

In [16]:
df.columns[df.isnull().sum() != 0]

Index(['rcTime'], dtype='str')

In [17]:
df["rcDist"].unique

<bound method Series.unique of 0        1300
1        1300
2        1300
3        1300
4        1300
         ...
15943    1200
15944    1200
15945    1200
15946    1200
15947    1200
Name: rcDist, Length: 15948, dtype: int64>

In [18]:
df["rcDist"].nunique()

10

In [19]:
df["rcNo"]

0         1
1         1
2         1
3         7
4         7
         ..
15943    10
15944    10
15945    10
15946    10
15947    10
Name: rcNo, Length: 15948, dtype: int64

In [20]:
df["rcDist"].value_counts()

rcDist
1200    4888
1400    3659
1300    2663
1800    1851
1700    1223
1600     932
1000     427
2000     279
2300      24
1900       2
Name: count, dtype: int64

In [21]:
df["rcDate"]

0        20230107
1        20230107
2        20230107
3        20230107
4        20230107
           ...
15943    20260426
15944    20260426
15945    20260426
15946    20260426
15947    20260426
Name: rcDate, Length: 15948, dtype: int64

In [23]:
df["rcDate"] = pd.to_datetime(df["rcDate"], errors="coerce")

df_2025 = df[df["rcDate"] >= "20250101"]

df_2025["rcDist"].value_counts()

Series([], Name: count, dtype: int64)